name = "Microstates"
uuid = "36161bb8-d084-4d22-844f-8ce7d076efe9"
authors = ["Jorge-Vinicius-Malosti-da-Silveira"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
